package GUI;

public enum LookAndFeelAssets {
	Button_BG,
	Button_Over,
	Button_Down,
	CheckBox_BG,
	CheckBox_Over,
	CheckBox_Down,
	Panel_BG,
	Scrollbar_BG,
	ScrollbarButton_BG,
	ScrollbarButton_Down,
	SliderButton_Down,
	SliderButton_BG,
	SliderButton_Over,
	Slider_BG,
	Slider_Overlay,
	TextBox_BG,
	TextBox_Focus,
	Textarea_BG, 
	ScrollButton_BG, 
	ScrollButton_Over, 
	ScrollButton_Down, 
	ScrollbarButton_Over, 
	HorisontalScrollbarButton_BG, 
	HorisontalScrollbarButton_Over, 
	HorisontalScrollbarButton_Down, 
	VerticalSlider_BG,
	VerticalSlider_Overlay, HorisontalScrollbar_BG,
}
